#!/bin/bash

# sudo docker run --privileged --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro  -it bhima/e2e-tests:v1 bash

# Clean out old container (if it exists)
if (sudo docker ps -a | grep bhima-e2e-server) >& /dev/null; then
    sudo docker rm bhima-e2e-server
fi

# Run a new container
sudo docker run \
  --name bhima-e2e-server \
  --hostname bhima \
  -e "DEFAULT_BHIMA_DB_PASSWORD=$(openssl rand -hex 20)" \
  --volume /home/bhima/builds/scripts:/usr/src/app/scripts \
  --volume /home/bhima/mysql:/var/mysql \
  -it bhima/e2e-tests:v1 bash
