#!/bin/bash

# sudo docker run --privileged --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro  -it bhima/e2e-tests:v1 bash

# Refresh the setup.bash script
sudo docker cp setup.bash bhima-e2e-server:

# Clean out old container
sudo docker rm bhima-e2e-server

# Run a new container
sudo docker run \
  --name bhima-e2e-server \
  --hostname bhima \
  --volume /home/bhima/mysql:/var/mysql \
  -it bhima/e2e-tests:v1 bash
